#!/usr/bin/env python
"""Pipeline-fidelity check for the M023 spike (separate 3.11 venv).

Scores fresh synthetic episodes generated by the upstream ``cua_s1.synth``
generator through the SAME loading/softmax path the spike uses, and prints
top-1 accuracy plus the per-action breakdown and the training label
vocabularies. Run:

    .venv-cua-s1/bin/python scripts/cua_s1_validate.py --episodes 30

A high top-1 (the published validation top-1 is 0.9994) proves the spike's
scoring pipeline reproduces the upstream contract; the measured decisions
for the repository's field sets are then genuine model output, not an
integration artifact.
"""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pin-dir", default=str(REPO_ROOT / "models" / "cua-s1-forms"))
    parser.add_argument("--episodes", type=int, default=30)
    parser.add_argument("--batch", type=int, default=64)
    args = parser.parse_args()

    import torch
    from cua_s1 import synth
    from cua_s1.concepts import (FORM_TITLES, NON_SUBMIT_BUTTONS,
                                 OPTIONAL_CHECKBOXES, REQUIRED_CHECKBOXES,
                                 SUBMIT_LABELS)
    from cua_s1.model import ChoiceExample, load_checkpoint

    weights = Path(args.pin_dir) / "cua-s1-forms.safetensors"
    model, collator, _config = load_checkpoint(weights, "cpu")

    rows = []
    for seed in range(args.episodes):
        rows.extend(synth.episode_rows(seed))
    print("fresh synthetic rows:", len(rows))

    correct = 0
    per, ok = Counter(), Counter()
    for index in range(0, len(rows), args.batch):
        batch = rows[index:index + args.batch]
        examples = [ChoiceExample(context=row["context"],
                                  options=tuple(row["options"]),
                                  label=row["label"]) for row in batch]
        with torch.no_grad():
            logits = model(collator(examples))
        probabilities = torch.softmax(logits, dim=-1)
        for row, row_probs in zip(batch, probabilities):
            pick = int(torch.argmax(row_probs[: len(row["options"])]))
            action = row["meta"]["action"]
            per[action] += 1
            if pick == row["label"]:
                correct += 1
                ok[action] += 1
    print("top1 over all rows: {:.4f}".format(correct / len(rows)))
    for action in sorted(per):
        print("  {:<6} {:>5} / {:>5}".format(action, ok[action], per[action]))

    print("REQUIRED_CHECKBOXES:", REQUIRED_CHECKBOXES)
    print("OPTIONAL_CHECKBOXES:", OPTIONAL_CHECKBOXES)
    print("SUBMIT_LABELS:", SUBMIT_LABELS)
    print("NON_SUBMIT_BUTTONS:", NON_SUBMIT_BUTTONS)
    print("FORM_TITLES:", FORM_TITLES)

    fill_sample = next(row for row in rows if row["meta"]["action"] == "fill")
    check_sample = next(row for row in rows if row["meta"]["action"] == "check")
    print("SAMPLE fill context:", repr(fill_sample["context"]))
    print("SAMPLE fill options:", fill_sample["options"][:3], "...")
    print("SAMPLE check context:", repr(check_sample["context"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
