"""Local Vision Assistant — deterministic event spine (Milestone 002).

Stdlib-only. No model, capture permission, Accessibility permission, or
external dependency is required or acquired to run this milestone. The only
images are synthetic fixtures generated by trusted code.
"""

__version__ = "0.2.0"
__milestone__ = "002"
